name: Default

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * SUN'

jobs:
  build-jvm:
    name: Build JVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test
        if: success()
        run: ./mvnw clean test
      - name: Package
        if: success()
        run: ./mvnw package
      - name: Build Docker Image
        if: success()
        run: ./mvnw k8s:build
      - name: Push Docker Image
        if: success()
        run: ./mvnw k8s:push
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build-native:
    name: Build Native
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test
        if: success()
        run: ./mvnw clean test -Pnative
      - name: Package
        if: success()
        run: ./mvnw clean package -Pnative
      - name: Build Docker Image
        if: success()
        run: ./mvnw k8s:build -Pnative
      - name: Push Docker Image
        if: success()
        run: ./mvnw k8s:push -Pnative
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}